### ISSUE TITLE
Tom Watson gets tech

### ISSUE THREAD

**Issue by zeroXten** [zeroXten/dotheyget.tech#1]
https://en.wikipedia.org/wiki/Tom_Watson_(Labour_politician)

**Comment by marksteward** [comment]
Weak placeholder quote from http://www.newstatesman.com/culture/2014/12/date-destiny-tom-watson-best-and-worst-games-2014:

> That’s the trouble with buying from a console’s online store. If the game is pap, you can’t take it back to the shop and sell it second-hand to recoup your losses.

**Comment by zeroXten** [comment]
Added. Different quote though.
