### ISSUE TITLE
Stella Creasy gets tech

### ISSUE THREAD

**Issue by marksteward** [zeroXten/dotheyget.tech#4]
> as somebody who was not able to make progress in tracking somebody who was harassing me online, because they were using the Tor network, the flipside of this is about our understanding of the technological capacities and limitations.

http://data.parliament.uk/writtenevidence/committeeevidence.svc/evidencedocument/science-and-technology-committee/investigatory-powers-bill-technology-issues/oral/24378.pdf

**Comment by zeroXten** [comment]
Added.
