### ISSUE TITLE
Theresa May doesn't get tech

### ISSUE THREAD

**Issue by marksteward** [zeroXten/dotheyget.tech#5]
> We know these powers are needed as technology changes and terrorists and criminals use ever more sophisticated ways to communicate.

http://www.theguardian.com/world/2015/oct/31/theresa-may-backtracks-on-internet-snooping

**Comment by zeroXten** [comment]
> Consider the case of a teenage girl going missing. At present we can ask her mobile provider for
> call records before she went missing which could be invaluable to finding her. But for Internet
> access, all we get is that the Internet was accessed 300 times. What would be useful would be to
> know she accessed twitter just before she went missing in the same way as we could see she
> make a phone call

http://www.me.uk/IPBill-evidence1.pdf

**Comment by zeroXten** [comment]
added
