### ISSUE TITLE
Chi Onwurah gets tech

### ISSUE THREAD

**Issue by marksteward** [zeroXten/dotheyget.tech#7]
> "This is very important, but cyber security is an area more than any other where we are only as strong as our weakest link, and there needs to be more general awareness throughout the population in a positive sense."
> 
> "The government will face a series of choices around how it collects and treats our data in the future, and if we’re not vigilant, citizens will see their data nationalised away from them and they should be concerned by that," she concluded.

http://www.computing.co.uk/ctg/news/2284569/government-is-not-spending-enough-on-cyber-security-awareness-says-labours-chi-onwurah

**Comment by zeroXten** [comment]
Added
